### ISSUE TITLE
App.js file is getting too big

### ISSUE THREAD

**Issue by Harmannz** [SWEN301-Group-Project/Group-Project#6]
We have placed all the routes in the app.js file. This has made it extremely big.  
I had tried to make a routes folder and create a file for the location route but was unsuccessful.   

> **Does anyone know how to make a routes folder and want to modularise the routes in app.js into separate files?**

**Comment by wildeelli** [comment]
Have done so for /cost (routes/routecost.js), /price (routes/price.js), and /location (routes/locations.js).
Looked at my 303 project because it is a working example.

Not marking as closed because mail and companies are still in app.js. Unsure if we have any other visible routes.

**Comment by Harmannz** [comment]
It looks much tidier than before. Closing as we finished the project
